# Generated by Django 5.2.3 on 2025-06-23 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian_dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='vet_assigned_animals', to=settings.AUTH_USER_MODEL),
        ),
    ]
