# Generated by Django 5.2.4 on 2025-07-22 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veterinarian_dashboard', '0004_patient_alter_vettask_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='anesthesia_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='breeding_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='cause_of_death',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='dewormer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='dip_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='dipping_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lab_test_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='mating_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='next_deworming_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='next_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='postmortem_findings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='reason_for_transfer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='referral_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='referred_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='report_type',
            field=models.CharField(choices=[('breeding', 'Breeding'), ('lab_diagnosis', 'Lab Diagnosis'), ('deworming', 'Deworming'), ('postmortem', 'Postmortem'), ('transfer', 'Transfer'), ('referral', 'Referral'), ('dipping', 'Dipping'), ('surgery', 'Surgery'), ('vaccination', 'Vaccination'), ('checkup', 'Routine Checkup')], default='surgery', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='sample_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='surgery_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='test_result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='transfer_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='transfer_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='vaccine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='medical_docs/'),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='vet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
