# Generated by Django 5.2.4 on 2025-08-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0005_remove_dailyactivityreport_user_and_more'),
        ('veterinarian_dashboard', '0006_emergencyreport_equipmentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='assigned_users',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='assigned_vet',
        ),
        migrations.RemoveField(
            model_name='vettask',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='vet',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.RemoveField(
            model_name='vettask',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='vettask',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='EmergencyReport',
        ),
        migrations.DeleteModel(
            name='EquipmentLog',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='VetTask',
        ),
    ]
