# Generated by Django 5.2.3 on 2025-06-23 06:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animal_assigned_users_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='assigned_users',
            field=models.ManyToManyField(blank=True, related_name='core_assigned_animals', to=settings.AUTH_USER_MODEL),
        ),
    ]
