# Generated by Django 5.2.3 on 2025-07-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_animal_branch_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='branch',
        ),
        migrations.AddField(
            model_name='animal',
            name='force_number',
            field=models.CharField(default='some_default_value', max_length=255),
        ),
    ]
