# Generated by Django 5.2.3 on 2025-07-14 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_animal_branch_animal_force_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch'),
        ),
    ]
