# Generated by Django 5.2.4 on 2025-07-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_animal_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='force_number',
            field=models.CharField(default='', max_length=255),
        ),
    ]
