# Generated by Django 5.2.4 on 2025-07-22 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_animal_force_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='animal',
            name='assigned_users',
            field=models.ManyToManyField(related_name='assigned_animals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animal',
            name='branch',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animal',
            name='force_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='animal',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='animal',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='animal_photos/'),
            preserve_default=False,
        ),
    ]
