# Generated by Django 5.2.4 on 2025-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_animal_date_of_birth_alter_animal_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='force_number',
            field=models.CharField(max_length=100),
        ),
    ]
