# Generated by Django 5.2.4 on 2025-07-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_message_branch_message_is_read_message_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
