# Generated by Django 5.2.4 on 2025-08-08 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_animal_options_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='branch_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
        migrations.AlterField(
            model_name='systemlog',
            name='branch',
            field=models.CharField(max_length=100),
        ),
    ]
