# Generated by Django 5.2.4 on 2025-08-08 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_systemlog_branch_fk_alter_systemlog_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='vettask',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
