# Generated by Django 5.2.4 on 2025-08-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_report_role_category_report_specific_report_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.branch'),
        ),
    ]
