# Generated by Django 5.2.3 on 2025-07-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_branch'),
        ('core', '0010_animal_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='branch_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(blank=True, choices=[('HQ', 'HQ'), ('Dodoma', 'Dodoma'), ('Iringa', 'Iringa'), ('TPS_Moshi', 'TPS Moshi')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('veterinarian', 'Veterinarian'), ('staff', 'Staff'), ('user', 'User')], max_length=20, null=True),
        ),
    ]
