# Generated by Django 5.2.3 on 2025-07-14 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_branch_fk_alter_customuser_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='branch_fk',
        ),
    ]
