# Generated by Django 5.2.3 on 2025-07-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_branch_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='branch',
            field=models.CharField(choices=[('Dodoma', 'Dodoma'), ('Iringa', 'Iringa'), ('HQ', 'HQ'), ('Tps_Moshi', 'Tps Moshi')], default='HQ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('veterinarian', 'Veterinarian'), ('staff', 'Staff'), ('user', 'User')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
