# Generated by Django 5.2.4 on 2025-08-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_remove_vettask_due_date_vettask_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vettask',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='vettask',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='vettask',
            name='assigned_to',
        ),
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
        migrations.DeleteModel(
            name='VetTask',
        ),
    ]
