# Generated by Django 5.2.4 on 2025-08-08 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard', '0004_alter_equipmentlog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivityreport',
            name='user',
        ),
        migrations.RemoveField(
            model_name='emergencyincident',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='emergencyincident',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='equipmentlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supportrequest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='usermessage',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='usernotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='AnimalLog',
        ),
        migrations.DeleteModel(
            name='DailyActivityReport',
        ),
        migrations.DeleteModel(
            name='EmergencyIncident',
        ),
        migrations.DeleteModel(
            name='EquipmentLog',
        ),
        migrations.DeleteModel(
            name='SupportRequest',
        ),
        migrations.DeleteModel(
            name='UserMessage',
        ),
        migrations.DeleteModel(
            name='UserNotification',
        ),
    ]
